plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - run_on_Azure.md
  - AZURE_Shenzhen_SAOS_14-4-2021_sparkStructuredStreaming_kafka_OnlineSampling.md

theme: jekyll-theme-slate
